version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    prestashop:
        build: presta_dock
        environment:
            DB_SERVER: db
            DB_USER: presta
            DB_PASSWD: presta
            DB_NAME: presta
            ADMIN_MAIL: nicolas.bonnet07@gmail.com
            ADMIN_PASSWD: Supre$Nini
        ports:
            - 80:80
        volumes:
            - ../../app:/var/www/html
        links:
          - db